// This file is @generated by prost-build.
/// Request to anchor a single entry.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnchorRequest {
    /// SHA-256 hash of the payload (32 bytes).
    /// Computed by NODE from streaming file/JSON content.
    #[prost(bytes = "vec", tag = "1")]
    pub payload_hash: ::prost::alloc::vec::Vec<u8>,
    /// SHA-256 hash of the metadata (32 bytes).
    /// Computed by NODE from JCS-canonicalized metadata JSON.
    #[prost(bytes = "vec", tag = "2")]
    pub metadata_hash: ::prost::alloc::vec::Vec<u8>,
    /// Cleartext metadata JSON (optional).
    /// Included in receipt for client convenience.
    #[prost(string, tag = "3")]
    pub metadata_json: ::prost::alloc::string::String,
    /// Client-provided external ID (optional).
    /// Preserved for client's reference tracking.
    #[prost(string, tag = "4")]
    pub external_id: ::prost::alloc::string::String,
}
/// Response for single entry submission.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnchorResponse {
    /// Generated entry UUID.
    #[prost(string, tag = "1")]
    pub entry_id: ::prost::alloc::string::String,
    /// Leaf index in Merkle tree (0-based).
    #[prost(uint64, tag = "2")]
    pub leaf_index: u64,
    /// Inclusion proof path (list of 32-byte sibling hashes).
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub inclusion_path: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Signed checkpoint covering this entry.
    #[prost(message, optional, tag = "4")]
    pub checkpoint: ::core::option::Option<Checkpoint>,
    /// Consistency proof for split-view protection (optional).
    /// Proves tree grew consistently from the last anchored tree size.
    /// Allows clients to verify the log hasn't forked since the last external anchor.
    #[prost(bytes = "vec", repeated, tag = "5")]
    pub consistency_proof: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Tree size from which consistency is proven (matches last anchor's tree_size).
    #[prost(uint64, tag = "6")]
    pub consistency_from: u64,
    /// TSA anchor (Tier-1 evidence) - included synchronously.
    /// Present when TSA is configured and successful.
    #[prost(message, optional, tag = "7")]
    pub tsa_anchor: ::core::option::Option<TsaAnchor>,
}
/// TSA (RFC 3161) anchor for Tier-1 evidence.
/// Provides immediate legal timestamp from a trusted third party.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TsaAnchor {
    /// URL of the TSA that signed this timestamp.
    /// Allows client to identify which TSA was used for verification.
    #[prost(string, tag = "1")]
    pub tsa_url: ::prost::alloc::string::String,
    /// Raw RFC 3161 TimeStampResp (DER encoded).
    /// Contains the full signed timestamp token for verification.
    #[prost(bytes = "vec", tag = "2")]
    pub tsa_response: ::prost::alloc::vec::Vec<u8>,
    /// Parsed timestamp from TSA (nanoseconds since Unix epoch).
    /// Extracted for convenience; authoritative value is in tsa_response.
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
}
/// Request to anchor multiple entries in one roundtrip.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnchorBatchRequest {
    /// List of entries to anchor (max 10,000).
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<AnchorRequest>,
}
/// Response for batch submission.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnchorBatchResponse {
    /// Results for each entry (same order as request).
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<AnchorEntryResult>,
    /// Single checkpoint covering the entire batch.
    #[prost(message, optional, tag = "2")]
    pub checkpoint: ::core::option::Option<Checkpoint>,
}
/// Individual entry result within a batch.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnchorEntryResult {
    /// Generated entry UUID.
    #[prost(string, tag = "1")]
    pub entry_id: ::prost::alloc::string::String,
    /// Leaf index in Merkle tree.
    #[prost(uint64, tag = "2")]
    pub leaf_index: u64,
    /// Inclusion proof path.
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub inclusion_path: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// Checkpoint represents a signed snapshot of the Merkle tree state.
/// This is the cryptographic commitment from the Sequencer.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Checkpoint {
    /// Origin ID - SHA-256 hash of the log's public key (32 bytes).
    /// Uniquely identifies this log instance.
    #[prost(bytes = "vec", tag = "1")]
    pub origin: ::prost::alloc::vec::Vec<u8>,
    /// Tree size at checkpoint time.
    /// Number of leaves in the tree when signed.
    #[prost(uint64, tag = "2")]
    pub tree_size: u64,
    /// Timestamp in nanoseconds since Unix epoch.
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
    /// Root hash of the Merkle tree (32 bytes).
    #[prost(bytes = "vec", tag = "4")]
    pub root_hash: ::prost::alloc::vec::Vec<u8>,
    /// Ed25519 signature over (origin || tree_size || timestamp || root_hash).
    /// 64 bytes.
    #[prost(bytes = "vec", tag = "5")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Key ID - SHA-256 hash of the signing public key (32 bytes).
    /// Allows verification against published keys.
    #[prost(bytes = "vec", tag = "6")]
    pub key_id: ::prost::alloc::vec::Vec<u8>,
}
/// Request to retrieve a receipt by entry UUID.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReceiptRequest {
    /// Entry UUID (standard UUID format).
    #[prost(string, tag = "1")]
    pub entry_id: ::prost::alloc::string::String,
    /// Whether to include external anchor attestations.
    #[prost(bool, tag = "2")]
    pub include_anchors: bool,
}
/// Full receipt response.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiptResponse {
    /// Entry metadata.
    #[prost(message, optional, tag = "1")]
    pub entry: ::core::option::Option<Entry>,
    /// Inclusion proof path (sibling hashes).
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub inclusion_path: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Signed checkpoint.
    #[prost(message, optional, tag = "3")]
    pub checkpoint: ::core::option::Option<Checkpoint>,
    /// Consistency proof for split-view protection (optional).
    /// Proves tree grew consistently from last anchored size.
    #[prost(message, optional, tag = "4")]
    pub consistency_proof: ::core::option::Option<ConsistencyProof>,
    /// External anchor attestations.
    #[prost(message, repeated, tag = "5")]
    pub anchors: ::prost::alloc::vec::Vec<ExternalAnchor>,
}
/// Entry metadata stored in the log.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entry {
    /// Entry UUID.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// SHA-256 hash of the original payload (32 bytes).
    #[prost(bytes = "vec", tag = "2")]
    pub payload_hash: ::prost::alloc::vec::Vec<u8>,
    /// SHA-256 hash of the metadata (32 bytes).
    #[prost(bytes = "vec", tag = "3")]
    pub metadata_hash: ::prost::alloc::vec::Vec<u8>,
    /// Cleartext metadata JSON (if was provided at anchor time).
    #[prost(string, tag = "4")]
    pub metadata_json: ::prost::alloc::string::String,
    /// Leaf index in Merkle tree.
    #[prost(uint64, tag = "5")]
    pub leaf_index: u64,
    /// Creation timestamp (nanoseconds since Unix epoch).
    #[prost(uint64, tag = "6")]
    pub created_at: u64,
    /// Client-provided external ID.
    #[prost(string, tag = "7")]
    pub external_id: ::prost::alloc::string::String,
}
/// Consistency proof between two tree sizes.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsistencyProof {
    /// Starting tree size (older).
    #[prost(uint64, tag = "1")]
    pub from_tree_size: u64,
    /// Proof path (intermediate hashes).
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub path: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// External anchor attestation (RFC 3161, OpenTimestamps, etc.).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExternalAnchor {
    /// Anchor type: "rfc3161", "ots", etc.
    #[prost(string, tag = "1")]
    pub anchor_type: ::prost::alloc::string::String,
    /// Hash that was anchored (typically root_hash).
    #[prost(bytes = "vec", tag = "2")]
    pub anchored_hash: ::prost::alloc::vec::Vec<u8>,
    /// Anchor timestamp (nanoseconds since Unix epoch).
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
    /// Raw anchor token (DER for RFC 3161, binary for OTS).
    #[prost(bytes = "vec", tag = "4")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    /// Additional metadata as JSON.
    #[prost(string, tag = "5")]
    pub metadata_json: ::prost::alloc::string::String,
}
/// Request for current tree head.
///
/// Empty - no parameters needed.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetTreeHeadRequest {}
/// Tree head response.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TreeHeadResponse {
    /// Current tree size (number of leaves).
    #[prost(uint64, tag = "1")]
    pub tree_size: u64,
    /// Current root hash (32 bytes).
    #[prost(bytes = "vec", tag = "2")]
    pub root_hash: ::prost::alloc::vec::Vec<u8>,
    /// Origin ID (32 bytes).
    #[prost(bytes = "vec", tag = "3")]
    pub origin: ::prost::alloc::vec::Vec<u8>,
    /// Latest signed checkpoint (if any).
    #[prost(message, optional, tag = "4")]
    pub latest_checkpoint: ::core::option::Option<Checkpoint>,
}
/// Request for public keys.
///
/// Empty - returns all active keys.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetPublicKeysRequest {}
/// Public keys response.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublicKeysResponse {
    /// List of public keys (current and historical).
    #[prost(message, repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<PublicKey>,
}
/// Public key information.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublicKey {
    /// Key ID - SHA-256 hash of the public key (32 bytes).
    #[prost(bytes = "vec", tag = "1")]
    pub key_id: ::prost::alloc::vec::Vec<u8>,
    /// Raw public key bytes (32 bytes for Ed25519).
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// Algorithm name (e.g., "ed25519").
    #[prost(string, tag = "3")]
    pub algorithm: ::prost::alloc::string::String,
    /// Key creation timestamp (nanoseconds since Unix epoch).
    #[prost(uint64, tag = "4")]
    pub created_at: u64,
}
/// Request to trigger external anchoring.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriggerAnchoringRequest {
    /// Anchor types to request: "rfc3161", "ots", etc.
    #[prost(string, repeated, tag = "1")]
    pub anchor_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Anchoring trigger response.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriggerAnchoringResponse {
    /// Tree size that was anchored.
    #[prost(uint64, tag = "1")]
    pub tree_size: u64,
    /// Root hash that was anchored.
    #[prost(bytes = "vec", tag = "2")]
    pub root_hash: ::prost::alloc::vec::Vec<u8>,
    /// Status for each requested anchor type.
    #[prost(message, repeated, tag = "3")]
    pub statuses: ::prost::alloc::vec::Vec<AnchoringStatus>,
}
/// Status of an anchoring operation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnchoringStatus {
    /// Anchor type.
    #[prost(string, tag = "1")]
    pub anchor_type: ::prost::alloc::string::String,
    /// Status: "completed", "pending", "failed".
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    /// Completion timestamp (if completed).
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
    /// Estimated time to finality in seconds (for pending).
    /// e.g., ~3600 for Bitcoin OTS.
    #[prost(uint64, tag = "4")]
    pub estimated_finality_secs: u64,
    /// Error message (if failed).
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
}
/// Request to upgrade a receipt with Bitcoin proof.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpgradeReceiptRequest {
    /// Entry UUID to upgrade.
    #[prost(string, tag = "1")]
    pub entry_id: ::prost::alloc::string::String,
}
/// Response for receipt upgrade.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpgradeReceiptResponse {
    /// Upgrade status.
    #[prost(enumeration = "UpgradeStatus", tag = "1")]
    pub status: i32,
    /// Full upgraded receipt as JSON (only if status == UPGRADED).
    /// Contains the complete receipt with consistency_proof and Bitcoin anchor.
    #[prost(bytes = "vec", tag = "2")]
    pub upgraded_receipt_json: ::prost::alloc::vec::Vec<u8>,
    /// Tree size in the original receipt (only if status == PENDING).
    /// Indicates what tree state the receipt was created at.
    #[prost(uint64, tag = "3")]
    pub receipt_tree_size: u64,
    /// Most recent Bitcoin anchor's tree_size (only if status == PENDING).
    /// Null/0 if no Bitcoin anchors exist yet.
    #[prost(uint64, tag = "4")]
    pub last_anchor_tree_size: u64,
    /// Estimated completion time (nanoseconds since Unix epoch, only if status == PENDING).
    /// When the next Bitcoin anchor is expected to cover this receipt.
    #[prost(uint64, tag = "5")]
    pub estimated_completion_unix: u64,
}
/// Bitcoin OTS anchor for Tier-2 evidence.
/// Provides permanent, immutable proof via Bitcoin blockchain.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BitcoinAnchor {
    /// Bitcoin block height containing the commitment.
    #[prost(uint64, tag = "1")]
    pub block_height: u64,
    /// Block timestamp (ISO 8601 format).
    #[prost(string, tag = "2")]
    pub block_time: ::prost::alloc::string::String,
    /// Tree size at the time of Bitcoin anchoring.
    /// Used to build consistency_proof in upgraded receipt.
    #[prost(uint64, tag = "3")]
    pub tree_size: u64,
    /// OpenTimestamps proof (binary format).
    #[prost(bytes = "vec", tag = "4")]
    pub ots_proof: ::prost::alloc::vec::Vec<u8>,
}
/// Health check request.
///
/// Empty.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthCheckRequest {}
/// Health check response.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckResponse {
    /// Whether the service is healthy.
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    /// Human-readable status message.
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Current tree size (for monitoring).
    #[prost(uint64, tag = "3")]
    pub tree_size: u64,
    /// Server uptime in seconds.
    #[prost(uint64, tag = "4")]
    pub uptime_secs: u64,
}
/// Status of a receipt upgrade operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UpgradeStatus {
    /// Bitcoin anchor doesn't cover this receipt yet.
    /// Client should retry later or poll estimated_completion.
    Pending = 0,
    /// Receipt successfully upgraded with Bitcoin proof.
    /// upgraded_receipt_json contains the full receipt.
    Upgraded = 1,
}
impl UpgradeStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "PENDING",
            Self::Upgraded => "UPGRADED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PENDING" => Some(Self::Pending),
            "UPGRADED" => Some(Self::Upgraded),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod sequencer_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// SequencerService handles all operations between NODE and SEQUENCER.
    /// NODEs connect to this service to submit entries and query receipts.
    /// All requests must include x-sequencer-token header for authentication.
    #[derive(Debug, Clone)]
    pub struct SequencerServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SequencerServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SequencerServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SequencerServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SequencerServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Submit a single entry and wait for signed checkpoint.
        /// Used for low-latency individual requests.
        pub async fn anchor_entry(
            &mut self,
            request: impl tonic::IntoRequest<super::AnchorRequest>,
        ) -> std::result::Result<tonic::Response<super::AnchorResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atl.sequencer.v1.SequencerService/AnchorEntry",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("atl.sequencer.v1.SequencerService", "AnchorEntry"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Submit a batch of entries for maximum throughput.
        /// Used when NODE accumulates multiple requests.
        pub async fn anchor_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::AnchorBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AnchorBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atl.sequencer.v1.SequencerService/AnchorBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("atl.sequencer.v1.SequencerService", "AnchorBatch"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get receipt by entry UUID.
        /// NODE proxies GET /v1/receipts/{id} through this method.
        pub async fn get_receipt(
            &mut self,
            request: impl tonic::IntoRequest<super::GetReceiptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReceiptResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atl.sequencer.v1.SequencerService/GetReceipt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("atl.sequencer.v1.SequencerService", "GetReceipt"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get current tree head.
        /// NODE proxies GET /v1/tree/head through this method.
        pub async fn get_tree_head(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTreeHeadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TreeHeadResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atl.sequencer.v1.SequencerService/GetTreeHead",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("atl.sequencer.v1.SequencerService", "GetTreeHead"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get public keys for verification.
        /// NODE proxies GET /v1/keys through this method.
        pub async fn get_public_keys(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPublicKeysRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PublicKeysResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atl.sequencer.v1.SequencerService/GetPublicKeys",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("atl.sequencer.v1.SequencerService", "GetPublicKeys"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Trigger external anchoring (TSA/OTS).
        /// NODE proxies POST /v1/anchors through this method.
        pub async fn trigger_anchoring(
            &mut self,
            request: impl tonic::IntoRequest<super::TriggerAnchoringRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TriggerAnchoringResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atl.sequencer.v1.SequencerService/TriggerAnchoring",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "atl.sequencer.v1.SequencerService",
                        "TriggerAnchoring",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Upgrade receipt with Bitcoin proof (Tier-2 evidence).
        /// NODE proxies GET /v1/receipts/{id}/upgrade through this method.
        pub async fn upgrade_receipt(
            &mut self,
            request: impl tonic::IntoRequest<super::UpgradeReceiptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpgradeReceiptResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atl.sequencer.v1.SequencerService/UpgradeReceipt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "atl.sequencer.v1.SequencerService",
                        "UpgradeReceipt",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Health check for connection monitoring.
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atl.sequencer.v1.SequencerService/HealthCheck",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("atl.sequencer.v1.SequencerService", "HealthCheck"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod sequencer_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SequencerServiceServer.
    #[async_trait]
    pub trait SequencerService: std::marker::Send + std::marker::Sync + 'static {
        /// Submit a single entry and wait for signed checkpoint.
        /// Used for low-latency individual requests.
        async fn anchor_entry(
            &self,
            request: tonic::Request<super::AnchorRequest>,
        ) -> std::result::Result<tonic::Response<super::AnchorResponse>, tonic::Status>;
        /// Submit a batch of entries for maximum throughput.
        /// Used when NODE accumulates multiple requests.
        async fn anchor_batch(
            &self,
            request: tonic::Request<super::AnchorBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AnchorBatchResponse>,
            tonic::Status,
        >;
        /// Get receipt by entry UUID.
        /// NODE proxies GET /v1/receipts/{id} through this method.
        async fn get_receipt(
            &self,
            request: tonic::Request<super::GetReceiptRequest>,
        ) -> std::result::Result<tonic::Response<super::ReceiptResponse>, tonic::Status>;
        /// Get current tree head.
        /// NODE proxies GET /v1/tree/head through this method.
        async fn get_tree_head(
            &self,
            request: tonic::Request<super::GetTreeHeadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TreeHeadResponse>,
            tonic::Status,
        >;
        /// Get public keys for verification.
        /// NODE proxies GET /v1/keys through this method.
        async fn get_public_keys(
            &self,
            request: tonic::Request<super::GetPublicKeysRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PublicKeysResponse>,
            tonic::Status,
        >;
        /// Trigger external anchoring (TSA/OTS).
        /// NODE proxies POST /v1/anchors through this method.
        async fn trigger_anchoring(
            &self,
            request: tonic::Request<super::TriggerAnchoringRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TriggerAnchoringResponse>,
            tonic::Status,
        >;
        /// Upgrade receipt with Bitcoin proof (Tier-2 evidence).
        /// NODE proxies GET /v1/receipts/{id}/upgrade through this method.
        async fn upgrade_receipt(
            &self,
            request: tonic::Request<super::UpgradeReceiptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpgradeReceiptResponse>,
            tonic::Status,
        >;
        /// Health check for connection monitoring.
        async fn health_check(
            &self,
            request: tonic::Request<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        >;
    }
    /// SequencerService handles all operations between NODE and SEQUENCER.
    /// NODEs connect to this service to submit entries and query receipts.
    /// All requests must include x-sequencer-token header for authentication.
    #[derive(Debug)]
    pub struct SequencerServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SequencerServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SequencerServiceServer<T>
    where
        T: SequencerService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/atl.sequencer.v1.SequencerService/AnchorEntry" => {
                    #[allow(non_camel_case_types)]
                    struct AnchorEntrySvc<T: SequencerService>(pub Arc<T>);
                    impl<
                        T: SequencerService,
                    > tonic::server::UnaryService<super::AnchorRequest>
                    for AnchorEntrySvc<T> {
                        type Response = super::AnchorResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AnchorRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SequencerService>::anchor_entry(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AnchorEntrySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atl.sequencer.v1.SequencerService/AnchorBatch" => {
                    #[allow(non_camel_case_types)]
                    struct AnchorBatchSvc<T: SequencerService>(pub Arc<T>);
                    impl<
                        T: SequencerService,
                    > tonic::server::UnaryService<super::AnchorBatchRequest>
                    for AnchorBatchSvc<T> {
                        type Response = super::AnchorBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AnchorBatchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SequencerService>::anchor_batch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AnchorBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atl.sequencer.v1.SequencerService/GetReceipt" => {
                    #[allow(non_camel_case_types)]
                    struct GetReceiptSvc<T: SequencerService>(pub Arc<T>);
                    impl<
                        T: SequencerService,
                    > tonic::server::UnaryService<super::GetReceiptRequest>
                    for GetReceiptSvc<T> {
                        type Response = super::ReceiptResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetReceiptRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SequencerService>::get_receipt(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetReceiptSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atl.sequencer.v1.SequencerService/GetTreeHead" => {
                    #[allow(non_camel_case_types)]
                    struct GetTreeHeadSvc<T: SequencerService>(pub Arc<T>);
                    impl<
                        T: SequencerService,
                    > tonic::server::UnaryService<super::GetTreeHeadRequest>
                    for GetTreeHeadSvc<T> {
                        type Response = super::TreeHeadResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTreeHeadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SequencerService>::get_tree_head(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTreeHeadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atl.sequencer.v1.SequencerService/GetPublicKeys" => {
                    #[allow(non_camel_case_types)]
                    struct GetPublicKeysSvc<T: SequencerService>(pub Arc<T>);
                    impl<
                        T: SequencerService,
                    > tonic::server::UnaryService<super::GetPublicKeysRequest>
                    for GetPublicKeysSvc<T> {
                        type Response = super::PublicKeysResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPublicKeysRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SequencerService>::get_public_keys(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPublicKeysSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atl.sequencer.v1.SequencerService/TriggerAnchoring" => {
                    #[allow(non_camel_case_types)]
                    struct TriggerAnchoringSvc<T: SequencerService>(pub Arc<T>);
                    impl<
                        T: SequencerService,
                    > tonic::server::UnaryService<super::TriggerAnchoringRequest>
                    for TriggerAnchoringSvc<T> {
                        type Response = super::TriggerAnchoringResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TriggerAnchoringRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SequencerService>::trigger_anchoring(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TriggerAnchoringSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atl.sequencer.v1.SequencerService/UpgradeReceipt" => {
                    #[allow(non_camel_case_types)]
                    struct UpgradeReceiptSvc<T: SequencerService>(pub Arc<T>);
                    impl<
                        T: SequencerService,
                    > tonic::server::UnaryService<super::UpgradeReceiptRequest>
                    for UpgradeReceiptSvc<T> {
                        type Response = super::UpgradeReceiptResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpgradeReceiptRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SequencerService>::upgrade_receipt(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpgradeReceiptSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atl.sequencer.v1.SequencerService/HealthCheck" => {
                    #[allow(non_camel_case_types)]
                    struct HealthCheckSvc<T: SequencerService>(pub Arc<T>);
                    impl<
                        T: SequencerService,
                    > tonic::server::UnaryService<super::HealthCheckRequest>
                    for HealthCheckSvc<T> {
                        type Response = super::HealthCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SequencerService>::health_check(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthCheckSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SequencerServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "atl.sequencer.v1.SequencerService";
    impl<T> tonic::server::NamedService for SequencerServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
