//! Generated protobuf code re-exports
//!
//! This module includes the code generated by tonic-build from proto/sequencer.proto.
//! The generated code is placed in src/grpc/ by build.rs.

// Include the generated protobuf code
tonic::include_proto!("atl.sequencer.v1");
